### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by pervoj** [vala-lang/vala-www#15]
It would be nice to have in the future the website translatable. It is not necessary right away, but in the future it will be good. Especialy the tutorial section.

**Comment by colinkiama** [comment]
Well there is some support already. See: https://www.getzola.org/documentation/content/multilingual/

**Comment by lw64** [comment]
I don't think that translating especially tutorials is a good idea. Maintaining them will become a nightmare. Everytime they get updated, they also need to be in all translations.

**Comment by nahuelwexd** [comment]
I agree that it will be quite challenging, but at the same time I think there will be quite a few who would like to be able to read the tutorials in their native language.

Maybe what should be done is to put a warning that the tutorial may not be up-to-date.

**Comment by lw64** [comment]
The vala community is not that large that we would have the resources to write and maintain tutorials, and also the main page I think, in different languages just because it would be more comfortable for a few people. We have much higher priority tasks to do.

**Comment by nahuelwexd** [comment]
That argument doesn't convince me. It's not like we're going to translate those tutorials, but someone else with enough time

We provide the infrastructure and that's it, then whoever wants to translate can do it. Just like it works in any other project

**Comment by lw64** [comment]
Yeah. But if there is already someone spending some amount of work on vala, we should encourage them to do more important stuff.

**Comment by nahuelwexd** [comment]
Not everyone is knowledgeable enough to contribute everywhere. It is likely that those who come forward to help translate the tutorials are those who are learning from the tutorials, and during their learning they translate them.

**Comment by lw64** [comment]
I agree. I would just not highlight the translation ability too much.

**Comment by colinkiama** [comment]
I haven't forgot. I was figuring out the ways this can be done.n

As far as I know, we can:
1) Creating different versions of markdown content. See: https://www.getzola.org/documentation/content/multilingual/#content
2) Translate strings defined in `config.toml` with the [`trans`](https://www.getzola.org/documentation/templates/overview/#trans) filter.

Method 1 Can be used for the majority of the site and method 2 would primarily be used for the home page since, the homepage the majority of the homepage's layout and contents are defined in it's template (index.html).

Method 1 can be used right now. You're all free to translate the markdown files under `/content`.

Things like the home page, header and footer content need translation maps to be set up first (Method 2). Feel free to try this too if you want. I'd appreciate it!
